// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tedd.AIOptimizeSql.Database;

#nullable disable

namespace Tedd.AIOptimizeSql.Database.Sqlite.Migrations
{
    [DbContext(typeof(AIOptimizeDbContext))]
    partial class AIOptimizeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AIConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AIConnections");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AgentTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DatabaseAnalysisId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HypothesisId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseAnalysisId");

                    b.HasIndex("HypothesisId");

                    b.ToTable("AgentTasks");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AnalysisFinding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabaseAnalysisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evidence")
                        .HasColumnType("TEXT");

                    b.Property<double>("ImpactScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObjectSchema")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ProposedExperimentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Recommendation")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecommendationSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseAnalysisId");

                    b.HasIndex("ProposedExperimentId");

                    b.ToTable("AnalysisFindings");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.BenchmarkRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ActualPlanXml")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Messages")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalLobLogicalReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLobPageServerReadAheadReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLobPageServerReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLobPhysicalReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLobReadAheadReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalLogicalReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPageServerReadAheadReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPageServerReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPhysicalReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalReadAheadReads")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalScanCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalServerCpuTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalServerElapsedTimeMs")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalTimeMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("BenchmarkRuns");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AIConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiSummaryMarkdown")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DatabaseConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnableWebSearch")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeStoredProceduresAndViews")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxAiFindings")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetricsSnapshotJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetricsSummaryMarkdown")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AIConnectionId");

                    b.HasIndex("DatabaseConnectionId");

                    b.ToTable("DatabaseAnalyses");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysisLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabaseAnalysisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DatabaseAnalysisId");

                    b.ToTable("DatabaseAnalysisLogs");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AIConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnalyzeOnly")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AIConnectionId");

                    b.ToTable("DatabaseConnections");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AiConversation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AIConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DatabaseConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ElapsedMs")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("InputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Model")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("OutputTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Provider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RelatedDatabaseAnalysisId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedExperimentId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedHypothesisId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RelatedResearchIterationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<long>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AIConnectionId");

                    b.HasIndex("DatabaseConnectionId");

                    b.HasIndex("StartedAt");

                    b.ToTable("AiConversations");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AIConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BenchmarkSql")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DatabaseConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperimentPostRunSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExperimentPreRunSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("HypothesisPostRunSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("HypothesisPreRunSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("Instructions")
                        .HasColumnType("TEXT");

                    b.Property<string>("IsolationMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputVerificationMode")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputVerificationSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("SandboxDatabaseName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SandboxSchemaName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("SandboxSetupSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("SandboxTeardownSql")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AIConnectionId");

                    b.HasIndex("DatabaseConnectionId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Hypothesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BenchmarkRunIdAfter")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BenchmarkRunIdBefore")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildsOnHypothesisId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<float>("ImpovementPercentage")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("OptimizeRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OptimizeSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("OutputMatchesBaseline")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ResearchIterationId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RevertRetryCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RevertSql")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("TimeUsedMs")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkRunIdAfter");

                    b.HasIndex("BenchmarkRunIdBefore");

                    b.HasIndex("BuildsOnHypothesisId");

                    b.HasIndex("ResearchIterationId");

                    b.ToTable("Hypotheses");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.HypothesisLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HypothesisId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("HypothesisId");

                    b.ToTable("HypothesisLogs");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AIConnectionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AiModelUsed")
                        .HasColumnType("TEXT");

                    b.Property<string>("AiProviderUsed")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int?>("BaselineBenchmarkRunId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaselineOutputHash")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Hints")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastMessage")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxNumberOfHypotheses")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RegisteredBaseTables")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SandboxProvisioned")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaDiscoveryMarkdown")
                        .HasColumnType("TEXT");

                    b.Property<string>("SchemaDiscoveryResultJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AIConnectionId");

                    b.HasIndex("BaselineBenchmarkRunId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ResearchIterations");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIterationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResearchIterationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Source")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ResearchIterationId");

                    b.ToTable("ResearchIterationLogs");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.RunQueue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResearchIterationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ResearchIterationId")
                        .IsUnique();

                    b.ToTable("RunQueue");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AgentTask", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysis", "DatabaseAnalysis")
                        .WithMany()
                        .HasForeignKey("DatabaseAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.Hypothesis", "Hypothesis")
                        .WithMany()
                        .HasForeignKey("HypothesisId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("DatabaseAnalysis");

                    b.Navigation("Hypothesis");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AnalysisFinding", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysis", "DatabaseAnalysis")
                        .WithMany("Findings")
                        .HasForeignKey("DatabaseAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.Experiment", "ProposedExperiment")
                        .WithMany()
                        .HasForeignKey("ProposedExperimentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DatabaseAnalysis");

                    b.Navigation("ProposedExperiment");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysis", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.AIConnection", "AIConnection")
                        .WithMany()
                        .HasForeignKey("AIConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.DatabaseConnection", "DatabaseConnection")
                        .WithMany()
                        .HasForeignKey("DatabaseConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AIConnection");

                    b.Navigation("DatabaseConnection");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysisLog", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysis", "DatabaseAnalysis")
                        .WithMany("Logs")
                        .HasForeignKey("DatabaseAnalysisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DatabaseAnalysis");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseConnection", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.AIConnection", "AIConnection")
                        .WithMany()
                        .HasForeignKey("AIConnectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AIConnection");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AiConversation", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.AIConnection", "AIConnection")
                        .WithMany()
                        .HasForeignKey("AIConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.DatabaseConnection", "DatabaseConnection")
                        .WithMany()
                        .HasForeignKey("DatabaseConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AIConnection");

                    b.Navigation("DatabaseConnection");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Experiment", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.AIConnection", "AIConnection")
                        .WithMany()
                        .HasForeignKey("AIConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.DatabaseConnection", "DatabaseConnection")
                        .WithMany()
                        .HasForeignKey("DatabaseConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AIConnection");

                    b.Navigation("DatabaseConnection");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Hypothesis", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.BenchmarkRun", "BenchmarkRunAfter")
                        .WithMany()
                        .HasForeignKey("BenchmarkRunIdAfter")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.BenchmarkRun", "BenchmarkRunBefore")
                        .WithMany()
                        .HasForeignKey("BenchmarkRunIdBefore")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.Hypothesis", "BuilOptimizationHypothesis")
                        .WithMany()
                        .HasForeignKey("BuildsOnHypothesisId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", "ResearchIteration")
                        .WithMany("Hypotheses")
                        .HasForeignKey("ResearchIterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkRunAfter");

                    b.Navigation("BenchmarkRunBefore");

                    b.Navigation("BuilOptimizationHypothesis");

                    b.Navigation("ResearchIteration");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.HypothesisLog", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.Hypothesis", "Hypothesis")
                        .WithMany("Logs")
                        .HasForeignKey("HypothesisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hypothesis");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.AIConnection", "AIConnection")
                        .WithMany()
                        .HasForeignKey("AIConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.BenchmarkRun", "BaselineBenchmarkRun")
                        .WithMany()
                        .HasForeignKey("BaselineBenchmarkRunId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.Experiment", "Experiment")
                        .WithMany("ResearchIterations")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIConnection");

                    b.Navigation("BaselineBenchmarkRun");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIterationLog", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", "ResearchIteration")
                        .WithMany("Logs")
                        .HasForeignKey("ResearchIterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchIteration");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.RunQueue", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", "ResearchIteration")
                        .WithMany()
                        .HasForeignKey("ResearchIterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchIteration");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseAnalysis", b =>
                {
                    b.Navigation("Findings");

                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Experiment", b =>
                {
                    b.Navigation("ResearchIterations");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Hypothesis", b =>
                {
                    b.Navigation("Logs");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", b =>
                {
                    b.Navigation("Hypotheses");

                    b.Navigation("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
