// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tedd.AIOptimizeSql.Database;

#nullable disable

namespace Tedd.AIOptimizeSql.Database.Migrations
{
    [DbContext(typeof(AIOptimizeDbContext))]
    [Migration("20260413093105_HypothesisIdIdentity")]
    partial class HypothesisIdIdentity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.AIConnection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("AIConnections");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.BenchmarkRun", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ActualPlanXml")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Messages")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TotalLobLogicalReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalLobPageServerReadAheadReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalLobPageServerReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalLobPhysicalReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalLobReadAheadReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalLogicalReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalPageServerReadAheadReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalPageServerReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalPhysicalReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalReadAheadReads")
                        .HasColumnType("int");

                    b.Property<int>("TotalScanCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalServerCpuTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("TotalServerElapsedTimeMs")
                        .HasColumnType("int");

                    b.Property<int>("TotalTimeMs")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BenchmarkRuns");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.DatabaseConnection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.HasKey("Id");

                    b.ToTable("DatabaseConnections");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Experiment", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AIConnectionId")
                        .HasColumnType("int");

                    b.Property<string>("BenchmarkSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DatabaseConnectionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperimentPostRunSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExperimentPreRunSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HypothesisPostRunSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HypothesisPreRunSql")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Instructions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.HasKey("Id");

                    b.HasIndex("AIConnectionId");

                    b.HasIndex("DatabaseConnectionId");

                    b.ToTable("Experiments");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Hypothesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BenchmarkRunIdAfter")
                        .HasColumnType("int");

                    b.Property<int?>("BenchmarkRunIdBefore")
                        .HasColumnType("int");

                    b.Property<int?>("BuildsOnHypothesisId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ImpovementPercentage")
                        .HasColumnType("real");

                    b.Property<int>("ResearchIterationId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<long>("TimeUsedMs")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("BenchmarkRunIdAfter");

                    b.HasIndex("BenchmarkRunIdBefore");

                    b.HasIndex("BuildsOnHypothesisId");

                    b.HasIndex("ResearchIterationId");

                    b.ToTable("Hypotheses");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<int?>("AIConnectionId")
                        .HasColumnType("int");

                    b.Property<string>("AiModelUsed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AiProviderUsed")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExperimentId")
                        .HasColumnType("int");

                    b.Property<string>("Hints")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MaxNumberOfHypotheses")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("AIConnectionId");

                    b.HasIndex("ExperimentId");

                    b.ToTable("ResearchIterations");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.RunQueue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ResearchIterationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ResearchIterationId")
                        .IsUnique();

                    b.ToTable("RunQueue");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Experiment", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.AIConnection", "AIConnection")
                        .WithMany()
                        .HasForeignKey("AIConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.DatabaseConnection", "DatabaseConnection")
                        .WithMany()
                        .HasForeignKey("DatabaseConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AIConnection");

                    b.Navigation("DatabaseConnection");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Hypothesis", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.BenchmarkRun", "BenchmarkRunAfter")
                        .WithMany()
                        .HasForeignKey("BenchmarkRunIdAfter")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.BenchmarkRun", "BenchmarkRunBefore")
                        .WithMany()
                        .HasForeignKey("BenchmarkRunIdBefore")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.Hypothesis", "BuilOptimizationHypothesis")
                        .WithMany()
                        .HasForeignKey("BuildsOnHypothesisId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", "ResearchIteration")
                        .WithMany("Hypotheses")
                        .HasForeignKey("ResearchIterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BenchmarkRunAfter");

                    b.Navigation("BenchmarkRunBefore");

                    b.Navigation("BuilOptimizationHypothesis");

                    b.Navigation("ResearchIteration");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.AIConnection", "AIConnection")
                        .WithMany()
                        .HasForeignKey("AIConnectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.Experiment", "Experiment")
                        .WithMany("ResearchIterations")
                        .HasForeignKey("ExperimentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AIConnection");

                    b.Navigation("Experiment");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.RunQueue", b =>
                {
                    b.HasOne("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", "ResearchIteration")
                        .WithMany()
                        .HasForeignKey("ResearchIterationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ResearchIteration");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.Experiment", b =>
                {
                    b.Navigation("ResearchIterations");
                });

            modelBuilder.Entity("Tedd.AIOptimizeSql.Database.Models.ResearchIteration", b =>
                {
                    b.Navigation("Hypotheses");
                });
#pragma warning restore 612, 618
        }
    }
}
